@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/5e66e5b0-4ecc-4cc0-882d-ea3ea53cc238

### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias
		